{{- if ne .Values.type "job" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname" . }}
  labels:
  {{- include "labels" . | indent 4 }}
spec:
  replicas: {{.Values.replicas}}
  selector:
    matchLabels:
    {{- include "labels" . | indent 6 }}
  template:
    metadata:
      labels:
      {{- include "labels" . | indent 8 }}
    spec:
      containers:
        - name: {{.Values.name}}
          image: {{.Values.image.name}}:{{.Values.image.tag}}
          imagePullPolicy: Always
          volumeMounts:
          {{- include "mounts" . | indent 10 }}
          {{- if .Values.configmap.env }}
          envFrom:
          - configMapRef:
              name: {{ include "fullname" . }}-var
          {{- end }}
          {{- if .Values.secrets }}
          env:
          {{- range $key, $value := .Values.secrets }}
          - name: {{ $value.var }}
            valueFrom:
              secretKeyRef:
                name: {{ include "fullname" $ }}-secret
                key: {{ $value.key }}
          {{- end }}
          {{- end }}
          {{- if .Values.port }}
          ports:
            - containerPort: {{ .Values.port }}
              protocol: TCP
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe: {{- .Values.readinessProbe | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe }}
          livenessProbe: {{- .Values.livenessProbe | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
      {{- include "volumes" . | indent 6 }}
{{- end }}