{{- if .Values.ingress.enable -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "fullname" . }}-ing
  labels:
    {{- include "labels" . | indent 4 }}
  annotations:
    {{- include "annotation-ingress" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          {{- range $key,$value := .Values.ingress.paths }}
          - path: {{ $value.prefix }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "fullname" $ }}-svc
                port:
                  number: {{ $.Values.port }}
        {{- end }}
{{- end }}