{{- if eq .Values.type "job" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "fullname" . }}
  labels:
  {{- include "labels" . | indent 4 }}
spec:
  template:
    spec:
      containers:
      - name: {{.Values.name}}
        image: {{.Values.image.name}}:{{.Values.image.tag}}
        imagePullPolicy: Always
        volumeMounts:
        {{- include "mounts" . | indent 10 }}
        {{- if .Values.configmap.env }}
        envFrom:
        - configMapRef:
            name: {{ include "fullname" . }}-var
        {{- end }}
        {{- if .Values.secrets }}
        env:
        {{- range $key, $value := .Values.secrets }}
        - name: {{ $value.var }}
          valueFrom:
            secretKeyRef:
              name: {{ include "fullname" $ }}-secret
              key: {{ $value.key }}
        {{- end }}
        {{- end }}
      volumes:
      {{- include "volumes" . | indent 6 }}
      restartPolicy: Never
  backoffLimit: 3
{{- end -}}