{{- if .Values.secrets }}
# This is a SecretProviderClass example using user-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "fullname" . }}-secret-store
  labels:
{{ include "labels" . | indent 4 }}
spec:
  provider: azure
  secretObjects:
    - secretName: {{ include "fullname" . }}-secret
      type: Opaque
      data:
{{- range $key, $value := .Values.secrets }}
        - objectName: {{ $value.key }}
          key: {{ $value.key }}
{{- end }}
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"                                     # Set to true for using managed identity
    userAssignedIdentityID: "950b3d98-dd6e-4b99-bb74-8715b337e3e6"   # Set the clientID of the user-assigned managed identity to use
    keyvaultName: "kv-ae-eco-data-dev"                               # Set to the name of your key vault
    cloudName: ""                                                    # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects: |
      array:
  {{- range $key, $value := .Values.secrets }}
        - |
          objectName: {{ $value.key }}   # object name
          objectType: secret            # object types: secret, key, or cert
  {{- end }}
    tenantId: "0ae51e19-07c8-4e4b-bb6d-648ee58410f4"                 # The tenant ID of the key vault
{{- end }}
